version: '3'
services:
  empbank:
    container_name: empbank
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules 
    ports:
      - "3020:3020"
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgresql://jaymeson:Abcd1234*@postgresql:5432/empbank?schema=public

  postgresql:
    image: postgres:12
    container_name: postgresql
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jaymeson
      POSTGRES_PASSWORD: Abcd1234*
      POSTGRES_DB: empbank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
